AdnugDemo1/Models/UserClaimsViewModel.cs
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Security.Claims;

namespace AdnugDemo1.Models
{
    public class UserClaimsViewModel : AdnugDemoModel
    {
        [DisplayName(".NET Claim Types")]
        [Required]
        public IEnumerable<Claim> Claims { get; set; }

        public string CustomClaimType { get; set; }
    }
}

AdnugDemo1/Controllers/MembershipController.cs
using AdnugDemo1.Core;
using AdnugDemo1.Core.Extensions;
using AdnugDemo1.Models;
using BrockAllen.MembershipReboot;
using KesselRun.Extensions;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Web.Mvc;

namespace AdnugDemo1.Controllers
{
    public class MembershipController : Controller
    {
        private const string GeneralExceptionMessageForView = "An error has been logged. Please contact bla bla bla ...";
        private readonly AuthenticationService _authenticationService;
        private readonly UserAccountService _userAccountService;

        public MembershipController(AuthenticationService authenticationService)
        {
            _authenticationService = authenticationService;
            _userAccountService = _authenticationService.UserAccountService;
        }

        [AllowAnonymous]
        public ActionResult Index()
        {
            return View();
        }

        [AllowAnonymous]
        public ActionResult Login()
        {
            var loginInputModel = new LoginInputModel
            {
                ClientScript = LoginInputModel.BuildClientScript(),
                Title = "Demo Test This Login Page"
            };

            return View(loginInputModel);
        }


        [HttpPost, AllowAnonymous, ValidateJsonAntiForgeryToken]
        public ActionResult Login(LoginInputModel loginInputModel)
        {
            if (ModelState.IsValid)
            {
                var returnUrl = Server.UrlDecode(loginInputModel.ReturnUrl);

                UserAccount account;
                if (_userAccountService.AuthenticateWithUsernameOrEmail(
                    WebUiConstants.PasswordManagerTenant,
                    loginInputModel.Username,
                    loginInputModel.Password,
                    out account))
                {
                    _authenticationService.SignIn(account, loginInputModel.RememberMe); // loginInputModel.RememberMe

                    return
                        Json(new Dictionary<string, string>
                        {
                            {ClientScriptConstants.Result, ClientScriptConstants.LoggedIn},
                            {ClientScriptConstants.ReturnUrl, returnUrl}
                        });
                }

                ModelState.AddModelError(ClientScriptConstants.LoginFailed, "Invalid Username or Password");
            }

            return this.ModelStateJson(ModelState);
        }

        //[Authorize]
        public ActionResult CreateUser()
        {
            return View(new CreateUserInputModel
            {
                ClientScript = CreateUserInputModel.BuildClientScript(),
                ConfirmPassword = string.Empty,
                Email = string.Empty,
                Password = string.Empty,
                Title = "Register New User",
                Username = string.Empty
            });
        }

        [HttpPost, ValidateJsonAntiForgeryToken]
        public ActionResult CreateUser(CreateUserInputModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _userAccountService.CreateAccount(WebUiConstants.PasswordManagerTenant, model.Username,
                        model.Password, model.Email);

                    if (SecuritySettings.Instance.RequireAccountVerification)
                    {
                        return
                            Json(new Dictionary<string, string>
                            {
                                {ClientScriptConstants.Result, ClientScriptConstants.Success},
                                {ClientScriptConstants.Email, model.Email}
                            });
                    }
                    return View(ClientScriptConstants.UserCreated, true);
                }
                catch (ValidationException ex)
                {
                    ModelState.AddModelError(ClientScriptConstants.MembershipRebootValidationFailed, ex.Message);
                }
                catch (Exception exception)
                {
                    ModelState.AddModelError(ClientScriptConstants.ServerSideException, exception.Message);
                }

            }
            return this.ModelStateJson(ModelState);
        }

        [AllowAnonymous]
        public ActionResult ConfirmedEmail(string id)
        {
            var account = _userAccountService.GetByVerificationKey(id);

            if (account.HasPassword())
            {
                var confirmedEmailInputModel = new ConfirmedEmailInputModel
                {
                    ClientScript = ConfirmedEmailInputModel.BuildClientScript(),
                    Key = id,
                    Password = string.Empty,
                    Title = "Confirm Email"
                };
                return View(confirmedEmailInputModel);
            }

            return View();
        }

        [HttpPost, AllowAnonymous, ValidateJsonAntiForgeryToken]
        public ActionResult ConfirmedEmail(ConfirmedEmailInputModel confirmedEmailInputModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    UserAccount account;
                    _userAccountService.VerifyEmailFromKey(confirmedEmailInputModel.Key,
                        confirmedEmailInputModel.Password, out account);

                    // We can issue the cookie (sign them in) now that they have verified.
                    _authenticationService.SignIn(account);

                    return
                        Json(new Dictionary<string, string>
                        {
                            {ClientScriptConstants.Result, ClientScriptConstants.LoggedIn},
                            {ClientScriptConstants.ReturnUrl, Path.AltDirectorySeparatorChar.ToString()}
                        });
                }
                catch (ValidationException validationException)
                {
                    ModelState.AddModelError(ClientScriptConstants.EmailConfirmationFailed, validationException.Message);
                }
                catch (Exception exception)
                {
                    ModelState.AddModelError(ClientScriptConstants.ServerSideException, exception.Message);
                }
            }

            return this.ModelStateJson(ModelState);
        }

        public ActionResult Logout()
        {
            if (User.Identity.IsAuthenticated)
            {
                _authenticationService.SignOut();
                return Json(new Dictionary<string, string>
                {
                    {ClientScriptConstants.Result, ClientScriptConstants.Success},
                    {ClientScriptConstants.ReturnUrl, Path.AltDirectorySeparatorChar.ToString()}
                }, JsonRequestBehavior.AllowGet);
            }

            return View();
        }

        [AllowAnonymous]
        public ActionResult PasswordReset()
        {
            var passwordResetConfirmInputModel = new PasswordResetConfirmInputModel
            {
                ClientScript = PasswordResetConfirmInputModel.BuildClientScript(),
                Email = string.Empty,
                Title = "Password Reset Request"
            };

            return View(passwordResetConfirmInputModel);
        }

        [HttpPost, AllowAnonymous, ValidateJsonAntiForgeryToken]
        public ActionResult PasswordReset(PasswordResetConfirmInputModel passwordResetConfirmInputModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var account = _userAccountService.GetByEmail(WebUiConstants.PasswordManagerTenant,
                        passwordResetConfirmInputModel.Email);

                    if (account != null)
                    {
                        _userAccountService.ResetPassword(WebUiConstants.PasswordManagerTenant,
                            passwordResetConfirmInputModel.Email);
                        return Json(new Dictionary<string, string>
                        {
                            {ClientScriptConstants.Result, ClientScriptConstants.PasswordResetConfirmSuccess},
                            {ClientScriptConstants.Email, passwordResetConfirmInputModel.Email}
                        });
                    }

                    ModelState.AddModelError(string.Empty, "Invalid email");
                }
                catch (ValidationException ex)
                {
                    ModelState.AddModelError(string.Empty, ex.Message);
                }
            }

            return this.ModelStateJson(ModelState);
        }

        [AllowAnonymous]
        public ActionResult PasswordResetConfirm(string id)
        {
            var passwordResetConfirmInputModel = new ChangePasswordFromResetKeyInputModel
            {
                ClientScript = PasswordResetConfirmInputModel.BuildClientScript(),
                ConfirmPassword = string.Empty,
                Key = id,
                Password = string.Empty,
                Title = "Password Reset Input Screen"
            };

            return View(passwordResetConfirmInputModel);
        }

        [AllowAnonymous]
        [HttpPost, ValidateJsonAntiForgeryToken]
        public ActionResult PasswordResetConfirm(ChangePasswordFromResetKeyInputModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    UserAccount account;
                    if (_userAccountService.ChangePasswordFromResetKey(model.Key, model.Password, out account))
                    {
                        if (account.IsLoginAllowed && !account.IsAccountClosed)
                        {
                            _authenticationService.SignIn(account);

AdnugDemo1/Views/Membership/AddCLaim.cshtml
@model AdnugDemo1.Models.AddClaimInputModel

@section title
{
    @Model.Title
}

<div class="pure-g pure-u-1-8"></div>
<div id="mainContentWrap" class="pure-g pure-u-1-2 formEntry formEntryBox">

    <h2>@Model.Title</h2>
    
        @using (Html.BeginForm("AddClaim", "Membership", FormMethod.Post, new { id="addClaimForm", @class = "pure-form pure-form-stacked" }))
        {
            <div class="pure-g pure-u-1-4"></div>
            <div class="pure-g pure-u-1-2">
                @Html.AntiForgeryToken()
                
                @Html.HiddenFor(m => m.NewClaimType)
                
                <div id="stockClaimsWrapper">
                    @Html.LabelFor(m => m.ClaimTypes)
                    @Html.DropDownListFor(m => m.SelectedClaimType, new SelectList(Model.ClaimTypes, "Value", "Text"), "Choose a Claim", new { @class = "darkText" })
                </div>
                <div id="customClaimWrapper" class="initialHide">
                    @Html.LabelFor(m => m.CustomClaimType)
                    @Html.EditorFor(m => m.CustomClaimType)
                </div>

                or <a id="addClaimLabel" class="label label-warning">Add custom claim</a>
                
                @Html.LabelFor(m => m.NewClaimValue)
                @Html.EditorFor(m => m.NewClaimValue)

                <button id="createClaimButton" class="pure-button"><i class="fa fa-floppy-o"></i>&nbsp;Create Claim</button><div id="addClaimMsgLabelWrap" class="initialHide"></div>

            </div>

            <div class="pure-g pure-u-1-4"></div>
        }
        </div>
<div class="pure-g pure-u-1-8"></div>

@section scripts {
    @Html.ScriptRenderer(m => m.ClientScript)
    @Scripts.Render("~/bundles/utilities")
    @Scripts.Render("~/bundles/add-claim")
}

AdnugDemo1/Views/Membership/ConfirmedEmail.cshtml
@model AdnugDemo1.Models.ConfirmedEmailInputModel

@section title
{
    @Model.Title
}

<div class="pure-g pure-u-1-8"></div>

<div id="mainContentWrap" class="pure-g pure-u-1-2 formEntry formEntryBox">

    <section id="ConfirmUser">
        <h2>@Model.Title</h2>

        @Html.ValidationSummary("There was a problem with logging in: ", new { id = "confirmedEmailValidationSummary" })

        @using (Html.BeginForm("ConfirmedEmail", "Membership", FormMethod.Post, new { id = "confirmedEmailForm", @class = "pure-form pure-form-stacked" }))
        {
            @Html.AntiForgeryToken()

            <fieldset>
                <legend>@ViewBag.Title</legend>
                @Html.HiddenFor(m => m.Key)

                @Html.LabelFor(m => m.Password)
                @Html.EditorFor(m => m.Password)
                @Html.ValidationMessageFor(m => m.Password)

                <div class="pure-g pure-u-24-24">
                    <button id="ConfirmEmailButton" class="pure-button pure-button-active">Confirm Email</button><div id="loginMsgLabelWrap"></div>
                </div>
            </fieldset>
        }
    </section>
</div>

<div class="pure-g pure-u-1-8"></div>
@section scripts {
        @Html.ScriptRenderer(m => m.ClientScript)
        @Scripts.Render("~/bundles/utilities")
        @Scripts.Render("~/bundles/confirmed-email")
    }

AdnugDemo1/Views/Membership/CreateUser.cshtml
@model AdnugDemo1.Models.CreateUserInputModel
           
@section title
{
    @Model.Title
}

<div class="pure-g pure-u-1-8"></div>
<div id="mainContentWrap" class="pure-g pure-u-1-2 formEntry formEntryBox">
    <h2>Create a New User</h2>

    <section id="registerUser">
        @Html.ValidationSummary("There was a problem with user creation: ", new { id = "registerValidationSummary" })

        @using (Html.BeginForm("CreateUser", "Membership", FormMethod.Post, new { id = "createUserForm", @class = "pure-form pure-form-stacked" }))
        {
            @Html.AntiForgeryToken()
            <div class="pure-g pure-u-1-4"></div>
            <div class="pure-g pure-u-1-2">
                <fieldset>
                    <legend class="formEntry">@Model.Title</legend>

                    @Html.EditorForModel()

                    <div class="buttons">
                        <button id="registerNewUserButton" class="pure-button pure-button-active">Create User</button><div id="registerMsgLabelWrap"></div>
                    </div>

                </fieldset>
            </div>
            <div class="pure-g pure-u-1-4"></div>
        }
    </section>
    <section id="operationResult" class="initialHide">
        <p><span class="label label-success">Success</span></p>
        <p>You should receive an email shortly at <span id="emailText"></span>.</p>
        <p>It will contain instructions to verify your account so that you can login.</p>
        <p><button id="createAnotherUserButton" class="pure-button">Wanna Create Another?</button></p>
    </section>
</div>
<div class="pure-g pure-u-1-8"></div>

@section scripts {
    @Html.ScriptRenderer(m => m.ClientScript)
    @Scripts.Render("~/bundles/utilities")
    @Scripts.Render("~/bundles/register")
}

AdnugDemo1/Views/Membership/Login.cshtml
@model AdnugDemo1.Models.LoginInputModel

@section title
{
    @Model.Title
}           


<div class="pure-g pure-u-1-8"></div>
<div id="mainContentWrap" class="pure-g pure-u-1-2 formEntry formEntryBox">

    <h2>Login Here</h2>
    <section id="loginUser">
        
        @Html.ValidationSummary("There was a problem with logging in: ", new { id = "loginValidationSummary" })

        @using (Html.BeginForm("LogIn", "Membership", FormMethod.Post, new { id="logInForm", @class = "pure-form pure-form-stacked" }))
        {
            @Html.AntiForgeryToken()

            <div class="pure-g pure-u-1-4"></div>
            <div class="pure-g pure-u-1-2">
                <fieldset>
                    <legend class="formEntry">Log In</legend>
                    <div>
                        @Html.LabelFor(m => m.Username)
                        @Html.TextBoxFor(m => m.Username)
                    </div>
                    <div>
                        @Html.LabelFor(m => m.Password)
                        @Html.PasswordFor(m => m.Password)
                    </div>
                    <div>
                        <button id="loginSubmitButton" class="pure-button"><i class="glyphicon glyphicon-log-in"></i>&nbsp;Log In</button><div id="loginMsgLabelWrap"></div>
                        <label for="rememberMeCheckbox" class="pure-checkbox">
                            @Html.CheckBoxFor(m => m.RememberMe, new { id = "rememberMeCheckbox" }) @WebUiConstants.RememberMe
                        </label>
                    </div>
                </fieldset>
            </div>
            <div class="pure-g pure-u-1-4"></div>
        }
    </section>
    @Html.ActionLink("Create a new user", "CreateUser", "Membership")
</div>
<div class="pure-g pure-u-1-8"></div>

@section scripts {
    @Html.ScriptRenderer(m => m.ClientScript)
    @Scripts.Render("~/bundles/utilities")
    @Scripts.Render("~/bundles/login")
}

AdnugDemo1/Views/Membership/PasswordReset.cshtml
@model AdnugDemo1.Models.PasswordResetConfirmInputModel

@section title
{
    @Model.Title
}


<div class="pure-g pure-u-1-8"></div>
<div id="mainContentWrap" class="pure-g pure-u-1-2 formEntry formEntryBox">

    <h2>Reset Password Request</h2>
    <section id="resetPasswordSection">

        @Html.ValidationSummary("There was a problem with the email address: ", new { id = "passwordResetValidationSummary" })

        @using (Html.BeginForm("PasswordReset", "Membership", FormMethod.Post, new { id = "passwordReset", @class = "pure-form pure-form-stacked" }))
        {
            @Html.AntiForgeryToken()

            <div class="pure-g pure-u-1-8"></div>
            <div class="pure-g pure-u-5-8">
                <fieldset>
                    <legend class="formEntry">Enter Email Address</legend>
                    <div>
                        @Html.LabelFor(m => m.Email)
                        @Html.TextBoxFor(m => m.Email)
                    </div>
                    <div><button id="passwordResetConfirmSubmitButton" class="pure-button">Submit Email Address</button><div id="loginMsgLabelWrap"></div></div>
                </fieldset>
            </div>
        }
    </section>
    <section id="operationResult" class="initialHide">
        <p><span class="label label-success"><i class="fa fa-thumbs-o-up"></i>&nbsp;Done</span></p>
        <p>You should receive an email shortly at <span id="emailText"></span>.</p>
        <p>It will contain instructions with a link to change your password.</p>
    </section>
</div>
<div class="pure-g pure-u-1-8"></div>
@section scripts {
    @Html.ScriptRenderer(m => m.ClientScript)
    @Scripts.Render("~/bundles/utilities")
    @Scripts.Render("~/bundles/password-reset")
}

AdnugDemo1/Views/Membership/PasswordResetConfirm.cshtml
@model AdnugDemo1.Models.ChangePasswordFromResetKeyInputModel

@section title
{
    @Model.Title
}


<div class="pure-g pure-u-1-8"></div>
<div id="mainContentWrap" class="pure-g pure-u-1-2 formEntry formEntryBox">

    <h2>Reset Password</h2>
    <section id="resetPasswordSection">

        @Html.ValidationSummary("There was a problem with the details entered: ", new { id = "passwordResetValidationSummary" })

        @using (Html.BeginForm("PasswordResetConfirm", "Membership", FormMethod.Post, new { id = "passwordResetForm", @class = "pure-form pure-form-stacked" }))
        {
            @Html.AntiForgeryToken()

            <div class="pure-g pure-u-1-8"></div>
            <div class="pure-g pure-u-5-8">
                <fieldset>
                    <legend class="formEntry">Enter New Details</legend>
                    <div>
                        @Html.EditorForModel()
                    </div>
                    <div><button id="passwordResetSubmitButton" class="pure-button">Submit New Password</button><div id="loginMsgLabelWrap"></div></div>
                </fieldset>
            </div>
        }
    </section>
</div>
<div class="pure-g pure-u-1-8"></div>

@section scripts {
    @Html.ScriptRenderer(m => m.ClientScript)
    @Scripts.Render("~/bundles/utilities")
    @Scripts.Render("~/bundles/password-reset")
}

AdnugDemo1/Views/Membership/UserClaims.cshtml
@model AdnugDemo1.Models.UserClaimsViewModel
@{
    ViewBag.Title = "UserClaims";
}

<div class="pure-g pure-u-1-8"></div>
<div id="mainContentWrap" class="pure-g pure-u-3-4 claims">
    <h2>@Model.Title</h2>

    <ul>

        <div class="pure-g pure-u-1-1">
            @{
                foreach (var claim in Model.Claims)
                {
                    <li><div class="pure-g pure-u-1-2"><strong>Type:</strong> @claim.Type</div><div class="pure-g pure-u-1-2"><strong>Value:</strong> @claim.Value</div></li>
                }
            }
        </div>

    </ul>
</div>
<div class="pure-g pure-u-1-8"></div>