AdnugDemo1/Controllers/CredentialsController.cs
using AdnugDemo1.Models;
using CredentialsManager.Model;
using CredentialsManager.Services;
using System.Web.Mvc;

namespace AdnugDemo1.Controllers
{
    public class CredentialsController : Controller
    {
        private readonly ICredentialsService _credentialsService;
        private const string DataValueField = "Id";
        private const string DataTextField = "Name";

        public CredentialsController(ICredentialsService credentialsService)
        {
            _credentialsService = credentialsService;
        }

        public ActionResult CreateCredential()
        {
            var createCredentialInputModel = new CreateCredentialInputModel
            {
                Title = "Create New Credential",
                WebSites = new SelectList(_credentialsService.GetWebSites(), DataValueField, DataTextField)
            };

            return View(createCredentialInputModel);
        }

        [HttpPost]
        public ActionResult CreateCredential(CreateCredentialInputModel model)
        {
            var newCredential = new Credential
            {
                AssociatedEmail = model.AssociatedEmail,
                Comment = model.Comment,
                UserName = model.UserName,
                Password = model.Password,
                WebSiteId = model.Site
            };

            _credentialsService.AddCredential(newCredential);

            model.WebSites = new SelectList(_credentialsService.GetWebSites(), DataValueField, DataTextField); // should pull this from a cache

            return View(model);
        }

        public ActionResult CreateWebSite()
        {
            var webSiteModel = new WebSiteModel
            {
                Name= string.Empty,
                Title = "Add a WebSite"
            };
            return View(webSiteModel);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult CreateWebSite(WebSiteModel model)
        {
            _credentialsService.AddWebSite(new WebSite
            {
                Name = model.Name,
                Url = model.Url
            });

            return View(model);
        }
    }
}

AdnugDemo1/Views/Credentials/CreateCredential.cshtml
@model AdnugDemo1.Models.CreateCredentialInputModel

@section title{
    @Model.Title
}

<div class="pure-g pure-u-1-8"></div>
<div id="mainContentWrap" class="pure-g pure-u-1-2 formEntry formEntryBox">

    <h2>Create New Credential</h2>


    @using (Html.BeginForm("CreateCredential", "Credentials", FormMethod.Post, new { @class = "pure-form pure-form-stacked" }))
    {
        <div class="pure-g pure-u-1-4"></div>
        <div class="pure-g pure-u-1-2">

            @Html.AntiForgeryToken()

            @Html.LabelFor(m => m.UserName)
            @Html.EditorFor(m => m.UserName)

            @Html.LabelFor(m => m.Password)
            @Html.EditorFor(m => m.Password)

            @Html.LabelFor(m => m.AssociatedEmail)
            @Html.EditorFor(m => m.AssociatedEmail)

            @Html.LabelFor(m => m.Comment)
            @Html.EditorFor(m => m.Comment)


            @Html.LabelFor(m => m.WebSites)
            @Html.DropDownListFor(m => m.Site, new SelectList(Model.WebSites, "Value", "Text"), "Choose a Site", new { @class="darkText"})

            
            <button id="createCredentialButton" class="pure-button"><i class="fa fa-floppy-o"></i>&nbsp;Create Credential</button>

            </div>
            
        <div class="pure-g pure-u-1-4"></div>
        }
        </div>
<div class="pure-g pure-u-1-8"></div>

AdnugDemo1/Views/Credentials/CreateWebSite.cshtml
@model AdnugDemo1.Models.WebSiteModel

@section title
{
    @Model.Title
}


<div class="pure-g pure-u-1-8"></div>
<div id="mainContentWrap" class="pure-g pure-u-1-2 formEntry formEntryBox">

    <h2>@Model.Title</h2>

    @using (Html.BeginForm("CreateWebSite", "Credentials", FormMethod.Post, new { @class = "pure-form pure-form-stacked" }))
    {
        <div class="pure-g pure-u-1-4"></div>
        <div class="pure-g pure-u-1-2">

            @Html.AntiForgeryToken()

            @Html.LabelFor(m => m.Name)
            @Html.EditorFor(m => m.Name)
            @Html.LabelFor(m => m.Url)
            @Html.EditorFor(m => m.Url)

            <button id="createWebSiteButton" class="pure-button"><i class="fa fa-floppy-o"></i>&nbsp;Create Web Site</button>
        </div>

        <div class="pure-g pure-u-1-4"></div>

    }
</div>
<div class="pure-g pure-u-1-8"></div>